[build]
target = "riscv32im-unknown-none-elf"

[target.riscv32im-unknown-none-elf]
rustflags = [
    "-C", "panic=abort",
    "-C", "opt-level=3",
    "-C", "link-arg=--gc-sections",
    "-C", "link-arg=--no-merge-exidx-entries",
]
