-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [poker_settlement_core]: function definitions
import Aeneas
import PokerSettlementCore.Types
import PokerSettlementCore.FunsExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace poker_settlement_core

/-- [poker_settlement_core::plan::MAX_PLAYERS]
    Source: 'poker-settlement-core/src/plan.rs', lines 31:0-31:30
    Visibility: public -/
@[global_simps, irreducible] def plan.MAX_PLAYERS : Std.U8 := 9#u8

/-- [poker_settlement_core::plan::MAX_TOTAL_BET]
    Source: 'poker-settlement-core/src/plan.rs', lines 33:0-33:57
    Visibility: public -/
@[global_simps, irreducible]
def plan.MAX_TOTAL_BET : Std.U64 := 1000000000000000000#u64

/-- [poker_settlement_core::side_pot::seat_bit]:
    Source: 'poker-settlement-core/src/side_pot.rs', lines 20:0-22:1
    Visibility: public -/
def side_pot.seat_bit (j : Std.U8) : Result Std.U16 := do
  1#u16 <<< j

/-- [poker_settlement_core::side_pot::is_eligible]:
    Source: 'poker-settlement-core/src/side_pot.rs', lines 26:0-28:1
    Visibility: public -/
def side_pot.is_eligible (mask : Std.U16) (seat : Std.U8) : Result Bool := do
  let i ← side_pot.seat_bit seat
  let i1 ← lift (mask &&& i)
  ok (i1 != 0#u16)

/-- [poker_settlement_core::side_pot::{impl core::fmt::Debug for poker_settlement_core::side_pot::SidePot}::fmt]:
    Source: 'poker-settlement-core/src/side_pot.rs', lines 35:9-35:14
    Visibility: public -/
def side_pot.SidePot.Insts.CoreFmtDebug.fmt
  (self : side_pot.SidePot) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn := Dyn.mk _ core.fmt.DebugU64 self.amount
  let dyn1 :=
    Dyn.mk _ (core.fmt.DebugShared core.fmt.DebugU16) self.eligible_seats
  core.fmt.Formatter.debug_struct_field2_finish f (toStr "SidePot") (toStr
    "amount") dyn (toStr "eligible_seats") dyn1

/-- Trait implementation: [poker_settlement_core::side_pot::{impl core::fmt::Debug for poker_settlement_core::side_pot::SidePot}]
    Source: 'poker-settlement-core/src/side_pot.rs', lines 35:9-35:14 -/
@[reducible]
def side_pot.SidePot.Insts.CoreFmtDebug : core.fmt.Debug side_pot.SidePot := {
  fmt := side_pot.SidePot.Insts.CoreFmtDebug.fmt
}

/-- [poker_settlement_core::side_pot::{impl core::clone::Clone for poker_settlement_core::side_pot::SidePot}::clone]:
    Source: 'poker-settlement-core/src/side_pot.rs', lines 35:16-35:21
    Visibility: public -/
def side_pot.SidePot.Insts.CoreCloneClone.clone
  (self : side_pot.SidePot) : Result side_pot.SidePot := do
  ok self

/-- Trait implementation: [poker_settlement_core::side_pot::{impl core::clone::Clone for poker_settlement_core::side_pot::SidePot}]
    Source: 'poker-settlement-core/src/side_pot.rs', lines 35:16-35:21 -/
@[reducible]
def side_pot.SidePot.Insts.CoreCloneClone : core.clone.Clone side_pot.SidePot
  := {
  clone := side_pot.SidePot.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [poker_settlement_core::side_pot::{impl core::marker::Copy for poker_settlement_core::side_pot::SidePot}]
    Source: 'poker-settlement-core/src/side_pot.rs', lines 35:23-35:27 -/
@[reducible]
def side_pot.SidePot.Insts.CoreMarkerCopy : core.marker.Copy side_pot.SidePot
  := {
  cloneInst := side_pot.SidePot.Insts.CoreCloneClone
}

/-- Trait implementation: [poker_settlement_core::side_pot::{impl core::marker::StructuralPartialEq for poker_settlement_core::side_pot::SidePot}]
    Source: 'poker-settlement-core/src/side_pot.rs', lines 35:29-35:38 -/
@[reducible]
def side_pot.SidePot.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq side_pot.SidePot := {
}

/-- [poker_settlement_core::side_pot::{impl core::cmp::PartialEq<poker_settlement_core::side_pot::SidePot> for poker_settlement_core::side_pot::SidePot}::eq]:
    Source: 'poker-settlement-core/src/side_pot.rs', lines 35:29-35:38
    Visibility: public -/
def side_pot.SidePot.Insts.CoreCmpPartialEqSidePot.eq
  (self : side_pot.SidePot) (other : side_pot.SidePot) : Result Bool := do
  if self.amount = other.amount
  then ok (self.eligible_seats = other.eligible_seats)
  else ok false

/-- Trait implementation: [poker_settlement_core::side_pot::{impl core::cmp::PartialEq<poker_settlement_core::side_pot::SidePot> for poker_settlement_core::side_pot::SidePot}]
    Source: 'poker-settlement-core/src/side_pot.rs', lines 35:29-35:38 -/
@[reducible]
def side_pot.SidePot.Insts.CoreCmpPartialEqSidePot : core.cmp.PartialEq
  side_pot.SidePot side_pot.SidePot := {
  eq := side_pot.SidePot.Insts.CoreCmpPartialEqSidePot.eq
}

/-- [poker_settlement_core::side_pot::{impl core::cmp::Eq for poker_settlement_core::side_pot::SidePot}::assert_fields_are_eq]:
    Source: 'poker-settlement-core/src/side_pot.rs', lines 35:40-35:42
    Visibility: public -/
def side_pot.SidePot.Insts.CoreCmpEq.assert_fields_are_eq
  (self : side_pot.SidePot) : Result Unit := do
  ok ()

/-- Trait implementation: [poker_settlement_core::side_pot::{impl core::cmp::Eq for poker_settlement_core::side_pot::SidePot}]
    Source: 'poker-settlement-core/src/side_pot.rs', lines 35:40-35:42 -/
@[reducible]
def side_pot.SidePot.Insts.CoreCmpEq : core.cmp.Eq side_pot.SidePot := {
  partialEqInst := side_pot.SidePot.Insts.CoreCmpPartialEqSidePot
  assert_fields_are_eq := side_pot.SidePot.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [poker_settlement_core::side_pot::{impl borsh::ser::BorshSerialize for poker_settlement_core::side_pot::SidePot}::serialize]:
    Source: 'poker-settlement-core/src/side_pot.rs', lines 35:44-35:58
    Visibility: public -/
def side_pot.SidePot.Insts.BorshSerBorshSerialize.serialize
  {__W : Type} (coreiowriteWriteInst : core.io.write.Write __W)
  (self : side_pot.SidePot) (writer : __W) :
  Result ((core.result.Result Unit core.io.error.Error) × __W)
  := do
  let (r, writer1) ←
    U64.Insts.BorshSerBorshSerialize.serialize coreiowriteWriteInst self.amount
      writer
  let cf ← core.result.Result.Insts.CoreOpsTry.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue _ =>
    let (r1, writer2) ←
      U16.Insts.BorshSerBorshSerialize.serialize coreiowriteWriteInst
        self.eligible_seats writer1
    let cf1 ← core.result.Result.Insts.CoreOpsTry.branch r1
    match cf1 with
    | core.ops.control_flow.ControlFlow.Continue _ =>
      ok (core.result.Result.Ok (), writer2)
    | core.ops.control_flow.ControlFlow.Break residual =>
      let r2 ←
        core.result.Result.Insts.CoreOpsTry_traitFromResidualResult.from_residual
          Unit (core.convert.FromSame core.io.error.Error) residual
      ok (r2, writer2)
  | core.ops.control_flow.ControlFlow.Break residual =>
    let r1 ←
      core.result.Result.Insts.CoreOpsTry_traitFromResidualResult.from_residual
        Unit (core.convert.FromSame core.io.error.Error) residual
    ok (r1, writer1)

/-- Trait implementation: [poker_settlement_core::side_pot::{impl borsh::ser::BorshSerialize for poker_settlement_core::side_pot::SidePot}]
    Source: 'poker-settlement-core/src/side_pot.rs', lines 35:44-35:58 -/
@[reducible]
def side_pot.SidePot.Insts.BorshSerBorshSerialize : borsh.ser.BorshSerialize
  side_pot.SidePot := {
  serialize := fun {W : Type} (coreiowriteWriteInst : core.io.write.Write W) =>
    side_pot.SidePot.Insts.BorshSerBorshSerialize.serialize
    coreiowriteWriteInst
}

/-- [poker_settlement_core::side_pot::{impl borsh::de::BorshDeserialize for poker_settlement_core::side_pot::SidePot}::deserialize_reader]:
    Source: 'poker-settlement-core/src/side_pot.rs', lines 35:60-35:76
    Visibility: public -/
def side_pot.SidePot.Insts.BorshDeBorshDeserialize.deserialize_reader
  {__R : Type} (allocioreadReadInst : alloc.io.read.Read __R) (reader : __R) :
  Result ((core.result.Result side_pot.SidePot core.io.error.Error) × __R)
  := do
  let (r, reader1) ←
    U64.Insts.BorshDeBorshDeserialize.deserialize_reader allocioreadReadInst
      reader
  let cf ← core.result.Result.Insts.CoreOpsTry.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    let (r1, reader2) ←
      U16.Insts.BorshDeBorshDeserialize.deserialize_reader allocioreadReadInst
        reader1
    let cf1 ← core.result.Result.Insts.CoreOpsTry.branch r1
    match cf1 with
    | core.ops.control_flow.ControlFlow.Continue val1 =>
      ok (core.result.Result.Ok { amount := val, eligible_seats := val1 },
        reader2)
    | core.ops.control_flow.ControlFlow.Break residual =>
      let r2 ←
        core.result.Result.Insts.CoreOpsTry_traitFromResidualResult.from_residual
          side_pot.SidePot (core.convert.FromSame core.io.error.Error) residual
      ok (r2, reader2)
  | core.ops.control_flow.ControlFlow.Break residual =>
    let r1 ←
      core.result.Result.Insts.CoreOpsTry_traitFromResidualResult.from_residual
        side_pot.SidePot (core.convert.FromSame core.io.error.Error) residual
    ok (r1, reader1)

/-- Trait implementation: [poker_settlement_core::side_pot::{impl borsh::de::BorshDeserialize for poker_settlement_core::side_pot::SidePot}]
    Source: 'poker-settlement-core/src/side_pot.rs', lines 35:60-35:76 -/
@[reducible]
def side_pot.SidePot.Insts.BorshDeBorshDeserialize : borsh.de.BorshDeserialize
  side_pot.SidePot := {
  deserialize_reader := fun {R : Type} (allocioreadReadInst :
    alloc.io.read.Read R) =>
    side_pot.SidePot.Insts.BorshDeBorshDeserialize.deserialize_reader
    allocioreadReadInst
}

/-- [poker_settlement_core::side_pot::{poker_settlement_core::side_pot::SidePot}::new]:
    Source: 'poker-settlement-core/src/side_pot.rs', lines 46:4-51:5
    Visibility: public -/
def side_pot.SidePot.new
  (amount : Std.U64) (eligible_seats : Std.U16) : Result side_pot.SidePot := do
  ok { amount, eligible_seats }

/-- [poker_settlement_core::side_pot::{poker_settlement_core::side_pot::SidePot}::is_eligible]:
    Source: 'poker-settlement-core/src/side_pot.rs', lines 55:4-57:5
    Visibility: public -/
def side_pot.SidePot.is_eligible
  (self : side_pot.SidePot) (seat : Std.U8) : Result Bool := do
  side_pot.is_eligible self.eligible_seats seat

/-- [poker_settlement_core::side_pot::{impl core::fmt::Debug for poker_settlement_core::side_pot::SidePotError}::fmt]:
    Source: 'poker-settlement-core/src/side_pot.rs', lines 61:9-61:14
    Visibility: public -/
def side_pot.SidePotError.Insts.CoreFmtDebug.fmt
  (self : side_pot.SidePotError) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  match self with
  | side_pot.SidePotError.BetOverflow =>
    core.fmt.Formatter.write_str f (toStr "BetOverflow")
  | side_pot.SidePotError.LengthMismatch =>
    core.fmt.Formatter.write_str f (toStr "LengthMismatch")

/-- Trait implementation: [poker_settlement_core::side_pot::{impl core::fmt::Debug for poker_settlement_core::side_pot::SidePotError}]
    Source: 'poker-settlement-core/src/side_pot.rs', lines 61:9-61:14 -/
@[reducible]
def side_pot.SidePotError.Insts.CoreFmtDebug : core.fmt.Debug
  side_pot.SidePotError := {
  fmt := side_pot.SidePotError.Insts.CoreFmtDebug.fmt
}

/-- [poker_settlement_core::side_pot::{impl core::clone::Clone for poker_settlement_core::side_pot::SidePotError}::clone]:
    Source: 'poker-settlement-core/src/side_pot.rs', lines 61:16-61:21
    Visibility: public -/
def side_pot.SidePotError.Insts.CoreCloneClone.clone
  (self : side_pot.SidePotError) : Result side_pot.SidePotError := do
  ok self

/-- Trait implementation: [poker_settlement_core::side_pot::{impl core::clone::Clone for poker_settlement_core::side_pot::SidePotError}]
    Source: 'poker-settlement-core/src/side_pot.rs', lines 61:16-61:21 -/
@[reducible]
def side_pot.SidePotError.Insts.CoreCloneClone : core.clone.Clone
  side_pot.SidePotError := {
  clone := side_pot.SidePotError.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [poker_settlement_core::side_pot::{impl core::marker::Copy for poker_settlement_core::side_pot::SidePotError}]
    Source: 'poker-settlement-core/src/side_pot.rs', lines 61:23-61:27 -/
@[reducible]
def side_pot.SidePotError.Insts.CoreMarkerCopy : core.marker.Copy
  side_pot.SidePotError := {
  cloneInst := side_pot.SidePotError.Insts.CoreCloneClone
}

/-- Trait implementation: [poker_settlement_core::side_pot::{impl core::marker::StructuralPartialEq for poker_settlement_core::side_pot::SidePotError}]
    Source: 'poker-settlement-core/src/side_pot.rs', lines 61:29-61:38 -/
@[reducible]
def side_pot.SidePotError.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq side_pot.SidePotError := {
}

/-- [poker_settlement_core::side_pot::{impl core::cmp::PartialEq<poker_settlement_core::side_pot::SidePotError> for poker_settlement_core::side_pot::SidePotError}::eq]:
    Source: 'poker-settlement-core/src/side_pot.rs', lines 61:29-61:38
    Visibility: public -/
def side_pot.SidePotError.Insts.CoreCmpPartialEqSidePotError.eq
  (self : side_pot.SidePotError) (other : side_pot.SidePotError) :
  Result Bool
  := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  ok (self1 = other1)

/-- Trait implementation: [poker_settlement_core::side_pot::{impl core::cmp::PartialEq<poker_settlement_core::side_pot::SidePotError> for poker_settlement_core::side_pot::SidePotError}]
    Source: 'poker-settlement-core/src/side_pot.rs', lines 61:29-61:38 -/
@[reducible]
def side_pot.SidePotError.Insts.CoreCmpPartialEqSidePotError :
  core.cmp.PartialEq side_pot.SidePotError side_pot.SidePotError := {
  eq := side_pot.SidePotError.Insts.CoreCmpPartialEqSidePotError.eq
}

/-- Trait implementation: [poker_settlement_core::side_pot::{impl core::cmp::Eq for poker_settlement_core::side_pot::SidePotError}]
    Source: 'poker-settlement-core/src/side_pot.rs', lines 61:40-61:42 -/
@[reducible]
impl_def side_pot.SidePotError.Insts.CoreCmpEq : core.cmp.Eq
  side_pot.SidePotError := {
  partialEqInst := side_pot.SidePotError.Insts.CoreCmpPartialEqSidePotError
  assert_fields_are_eq := core.cmp.Eq.assert_fields_are_eq.default
    side_pot.SidePotError.Insts.CoreCmpEq
}

/-- [poker_settlement_core::side_pot::{impl core::fmt::Display for poker_settlement_core::side_pot::SidePotError}::fmt]:
    Source: 'poker-settlement-core/src/side_pot.rs', lines 61:44-61:60
    Visibility: public -/
def side_pot.SidePotError.Insts.CoreFmtDisplay.fmt
  (self : side_pot.SidePotError) (__formatter : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  match self with
  | side_pot.SidePotError.BetOverflow =>
    core.fmt.Formatter.write_str __formatter (toStr
      "total bets exceed MAX_TOTAL_BET, possible overflow")
  | side_pot.SidePotError.LengthMismatch =>
    core.fmt.Formatter.write_str __formatter (toStr
      "bets/folded/all_in vectors must have same length")

/-- Trait implementation: [poker_settlement_core::side_pot::{impl core::fmt::Display for poker_settlement_core::side_pot::SidePotError}]
    Source: 'poker-settlement-core/src/side_pot.rs', lines 61:44-61:60 -/
@[reducible]
def side_pot.SidePotError.Insts.CoreFmtDisplay : core.fmt.Display
  side_pot.SidePotError := {
  fmt := side_pot.SidePotError.Insts.CoreFmtDisplay.fmt
}

/-- Trait implementation: [poker_settlement_core::side_pot::{impl core::error::Error for poker_settlement_core::side_pot::SidePotError}]
    Source: 'poker-settlement-core/src/side_pot.rs', lines 61:44-61:60 -/
@[reducible]
def side_pot.SidePotError.Insts.CoreErrorError : core.error.Error
  side_pot.SidePotError := {
  fmtDebugInst := side_pot.SidePotError.Insts.CoreFmtDebug
  fmtDisplayInst := side_pot.SidePotError.Insts.CoreFmtDisplay
}

/-- [poker_settlement_core::side_pot::{impl core::fmt::Debug for poker_settlement_core::side_pot::SidePotResult}::fmt]:
    Source: 'poker-settlement-core/src/side_pot.rs', lines 75:9-75:14
    Visibility: public -/
def side_pot.SidePotResult.Insts.CoreFmtDebug.fmt
  (self : side_pot.SidePotResult) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn :=
    Dyn.mk _ (core.fmt.DebugShared (core.fmt.DebugVec
      side_pot.SidePot.Insts.CoreFmtDebug)) self.pots
  core.fmt.Formatter.debug_struct_field1_finish f (toStr "SidePotResult")
    (toStr "pots") dyn

/-- Trait implementation: [poker_settlement_core::side_pot::{impl core::fmt::Debug for poker_settlement_core::side_pot::SidePotResult}]
    Source: 'poker-settlement-core/src/side_pot.rs', lines 75:9-75:14 -/
@[reducible]
def side_pot.SidePotResult.Insts.CoreFmtDebug : core.fmt.Debug
  side_pot.SidePotResult := {
  fmt := side_pot.SidePotResult.Insts.CoreFmtDebug.fmt
}

/-- [poker_settlement_core::side_pot::{impl core::clone::Clone for poker_settlement_core::side_pot::SidePotResult}::clone]:
    Source: 'poker-settlement-core/src/side_pot.rs', lines 75:16-75:21
    Visibility: public -/
def side_pot.SidePotResult.Insts.CoreCloneClone.clone
  (self : side_pot.SidePotResult) : Result side_pot.SidePotResult := do
  let v ←
    alloc.vec.CloneVec.clone side_pot.SidePot.Insts.CoreCloneClone self.pots
  ok { pots := v }

/-- Trait implementation: [poker_settlement_core::side_pot::{impl core::clone::Clone for poker_settlement_core::side_pot::SidePotResult}]
    Source: 'poker-settlement-core/src/side_pot.rs', lines 75:16-75:21 -/
@[reducible]
def side_pot.SidePotResult.Insts.CoreCloneClone : core.clone.Clone
  side_pot.SidePotResult := {
  clone := side_pot.SidePotResult.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [poker_settlement_core::side_pot::{impl core::marker::StructuralPartialEq for poker_settlement_core::side_pot::SidePotResult}]
    Source: 'poker-settlement-core/src/side_pot.rs', lines 75:23-75:32 -/
@[reducible]
def side_pot.SidePotResult.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq side_pot.SidePotResult := {
}

/-- [poker_settlement_core::side_pot::{impl core::cmp::PartialEq<poker_settlement_core::side_pot::SidePotResult> for poker_settlement_core::side_pot::SidePotResult}::eq]:
    Source: 'poker-settlement-core/src/side_pot.rs', lines 75:23-75:32
    Visibility: public -/
def side_pot.SidePotResult.Insts.CoreCmpPartialEqSidePotResult.eq
  (self : side_pot.SidePotResult) (other : side_pot.SidePotResult) :
  Result Bool
  := do
  alloc.vec.partial_eq.PartialEqVec.eq
    side_pot.SidePot.Insts.CoreCmpPartialEqSidePot self.pots other.pots

/-- Trait implementation: [poker_settlement_core::side_pot::{impl core::cmp::PartialEq<poker_settlement_core::side_pot::SidePotResult> for poker_settlement_core::side_pot::SidePotResult}]
    Source: 'poker-settlement-core/src/side_pot.rs', lines 75:23-75:32 -/
@[reducible]
def side_pot.SidePotResult.Insts.CoreCmpPartialEqSidePotResult :
  core.cmp.PartialEq side_pot.SidePotResult side_pot.SidePotResult := {
  eq := side_pot.SidePotResult.Insts.CoreCmpPartialEqSidePotResult.eq
}

/-- [poker_settlement_core::side_pot::{impl core::cmp::Eq for poker_settlement_core::side_pot::SidePotResult}::assert_fields_are_eq]:
    Source: 'poker-settlement-core/src/side_pot.rs', lines 75:34-75:36
    Visibility: public -/
def side_pot.SidePotResult.Insts.CoreCmpEq.assert_fields_are_eq
  (self : side_pot.SidePotResult) : Result Unit := do
  ok ()

/-- Trait implementation: [poker_settlement_core::side_pot::{impl core::cmp::Eq for poker_settlement_core::side_pot::SidePotResult}]
    Source: 'poker-settlement-core/src/side_pot.rs', lines 75:34-75:36 -/
@[reducible]
def side_pot.SidePotResult.Insts.CoreCmpEq : core.cmp.Eq side_pot.SidePotResult
  := {
  partialEqInst := side_pot.SidePotResult.Insts.CoreCmpPartialEqSidePotResult
  assert_fields_are_eq :=
    side_pot.SidePotResult.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [poker_settlement_core::side_pot::{poker_settlement_core::side_pot::SidePotResult}::total]: loop body 0:
    Source: 'poker-settlement-core/src/side_pot.rs', lines 88:8-90:9
    Visibility: public -/
@[rust_loop_body]
def side_pot.SidePotResult.total_loop.body
  (v : alloc.vec.Vec side_pot.SidePot) (iter : core.ops.range.Range Std.Usize)
  (total : Std.U64) :
  Result (ControlFlow ((core.ops.range.Range Std.Usize) × Std.U64) Std.U64)
  := do
  let (o, iter1) ←
    core.iter.range.IteratorRange.next core.iter.range.StepUsize iter
  match o with
  | none => ok (done total)
  | some i =>
    let sp ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice
        side_pot.SidePot) v i
    let total1 ← total + sp.amount
    ok (cont (iter1, total1))

/-- [poker_settlement_core::side_pot::{poker_settlement_core::side_pot::SidePotResult}::total]: loop 0:
    Source: 'poker-settlement-core/src/side_pot.rs', lines 88:8-90:9
    Visibility: public -/
@[rust_loop]
def side_pot.SidePotResult.total_loop
  (iter : core.ops.range.Range Std.Usize) (v : alloc.vec.Vec side_pot.SidePot)
  (total : Std.U64) :
  Result Std.U64
  := do
  loop
    (fun (iter1, total1) => side_pot.SidePotResult.total_loop.body v iter1
      total1)
    (iter, total)

/-- [poker_settlement_core::side_pot::{poker_settlement_core::side_pot::SidePotResult}::total]:
    Source: 'poker-settlement-core/src/side_pot.rs', lines 84:4-92:5
    Visibility: public -/
def side_pot.SidePotResult.total
  (self : side_pot.SidePotResult) : Result Std.U64 := do
  let i := alloc.vec.Vec.len self.pots
  side_pot.SidePotResult.total_loop { start := 0#usize, «end» := i }
    self.pots 0#u64

/-- [poker_settlement_core::side_pot::insert_sorted_u64]: loop body 0:
    Source: 'poker-settlement-core/src/side_pot.rs', lines 103:4-105:5 -/
@[rust_loop_body]
def side_pot.insert_sorted_u64_loop.body
  (v : alloc.vec.Vec Std.U64) (x : Std.U64) (i : Std.Usize) :
  Result (ControlFlow Std.Usize Std.Usize)
  := do
  let i1 := alloc.vec.Vec.len v
  if i < i1
  then
    let i2 ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice Std.U64) v i
    if i2 < x
    then let i3 ← i + 1#usize
         ok (cont i3)
    else ok (done i)
  else ok (done i)

/-- [poker_settlement_core::side_pot::insert_sorted_u64]: loop 0:
    Source: 'poker-settlement-core/src/side_pot.rs', lines 103:4-105:5 -/
@[rust_loop]
def side_pot.insert_sorted_u64_loop
  (v : alloc.vec.Vec Std.U64) (x : Std.U64) (i : Std.Usize) :
  Result Std.Usize
  := do
  loop
    (fun i1 => side_pot.insert_sorted_u64_loop.body v x i1)
    i

/-- [poker_settlement_core::side_pot::insert_sorted_u64]:
    Source: 'poker-settlement-core/src/side_pot.rs', lines 101:0-107:1 -/
def side_pot.insert_sorted_u64
  (v : alloc.vec.Vec Std.U64) (x : Std.U64) :
  Result (alloc.vec.Vec Std.U64)
  := do
  let i ← side_pot.insert_sorted_u64_loop v x 0#usize
  alloc.vec.Vec.insert v i x

/-- [poker_settlement_core::side_pot::sum_bets]: loop body 0:
    Source: 'poker-settlement-core/src/side_pot.rs', lines 212:4-219:1 -/
@[rust_loop_body]
def side_pot.sum_bets_loop.body
  (iter : core.slice.iter.Iter Std.U64) (total : Std.U64) :
  Result (ControlFlow ((core.slice.iter.Iter Std.U64) × Std.U64)
    (core.result.Result Std.U64 side_pot.SidePotError))
  := do
  let (o, iter1) ← core.slice.iter.IteratorSliceIter.next iter
  match o with
  | none => ok (done (core.result.Result.Ok total))
  | some bet =>
    let o1 ← lift (U64.checked_add total bet)
    let r ← core.option.Option.ok_or o1 side_pot.SidePotError.BetOverflow
    let cf ← core.result.Result.Insts.CoreOpsTry.branch r
    match cf with
    | core.ops.control_flow.ControlFlow.Continue val =>
      if val > plan.MAX_TOTAL_BET
      then ok (done (core.result.Result.Err side_pot.SidePotError.BetOverflow))
      else ok (cont (iter1, val))
    | core.ops.control_flow.ControlFlow.Break residual =>
      let r1 ←
        core.result.Result.Insts.CoreOpsTry_traitFromResidualResult.from_residual
          Std.U64 (core.convert.FromSame side_pot.SidePotError) residual
      ok (done r1)

/-- [poker_settlement_core::side_pot::sum_bets]: loop 0:
    Source: 'poker-settlement-core/src/side_pot.rs', lines 212:4-219:1 -/
@[rust_loop]
def side_pot.sum_bets_loop
  (iter : core.slice.iter.Iter Std.U64) (total : Std.U64) :
  Result (core.result.Result Std.U64 side_pot.SidePotError)
  := do
  loop
    (fun (iter1, total1) => side_pot.sum_bets_loop.body iter1 total1)
    (iter, total)

/-- [poker_settlement_core::side_pot::sum_bets]:
    Source: 'poker-settlement-core/src/side_pot.rs', lines 210:0-219:1 -/
def side_pot.sum_bets
  (bets : Slice Std.U64) :
  Result (core.result.Result Std.U64 side_pot.SidePotError)
  := do
  let iter ←
    SharedSlice.Insts.CoreIterTraitsCollectIntoIteratorSharedIter.into_iter
      bets
  side_pot.sum_bets_loop iter 0#u64

/-- [poker_settlement_core::side_pot::push_or_merge]:
    Source: 'poker-settlement-core/src/side_pot.rs', lines 193:0-207:1 -/
def side_pot.push_or_merge
  (pots : alloc.vec.Vec side_pot.SidePot) (amount : Std.U64)
  (eligible : Std.U16) :
  Result (alloc.vec.Vec side_pot.SidePot)
  := do
  if amount = 0#u64
  then ok pots
  else
    if eligible = 0#u16
    then
      let b ← alloc.vec.Vec.is_empty Global pots
      if b
      then
        let sp ← side_pot.SidePot.new amount eligible
        alloc.vec.Vec.push pots sp
      else
        let (o, pots1) ← alloc.vec.Vec.pop Global pots
        match o with
        | none => ok pots1
        | some last =>
          let i ← last.amount + amount
          alloc.vec.Vec.push pots1 { last with amount := i }
    else
      let sp ← side_pot.SidePot.new amount eligible
      alloc.vec.Vec.push pots sp

/-- [poker_settlement_core::side_pot::slice_layer]: loop body 0:
    Source: 'poker-settlement-core/src/side_pot.rs', lines 178:4-188:5 -/
@[rust_loop_body]
def side_pot.slice_layer_loop.body
  (bets : Slice Std.U64) (folded : Slice Bool) (prev_level : Std.U64)
  (level : Std.U64) (iter : core.ops.range.Range Std.Usize) (amount : Std.U64)
  (eligible : Std.U16) :
  Result (ControlFlow ((core.ops.range.Range Std.Usize) × Std.U64 × Std.U16)
    (Std.U64 × Std.U16))
  := do
  let (o, iter1) ←
    core.iter.range.IteratorRange.next core.iter.range.StepUsize iter
  match o with
  | none => ok (done (amount, eligible))
  | some j =>
    let bet ← Slice.index_usize bets j
    if bet > prev_level
    then
      let cap ← if bet < level
                  then ok bet
                  else ok level
      let i ← cap - prev_level
      let amount1 ← amount + i
      let b ← Slice.index_usize folded j
      if b
      then ok (cont (iter1, amount1, eligible))
      else
        let i1 ← lift (UScalar.cast .U8 j)
        let i2 ← side_pot.seat_bit i1
        let eligible1 ← lift (eligible ||| i2)
        ok (cont (iter1, amount1, eligible1))
    else ok (cont (iter1, amount, eligible))

/-- [poker_settlement_core::side_pot::slice_layer]: loop 0:
    Source: 'poker-settlement-core/src/side_pot.rs', lines 178:4-188:5 -/
@[rust_loop]
def side_pot.slice_layer_loop
  (iter : core.ops.range.Range Std.Usize) (bets : Slice Std.U64)
  (folded : Slice Bool) (prev_level : Std.U64) (level : Std.U64)
  (amount : Std.U64) (eligible : Std.U16) :
  Result (Std.U64 × Std.U16)
  := do
  loop
    (fun (iter1, amount1, eligible1) => side_pot.slice_layer_loop.body bets
      folded prev_level level iter1 amount1 eligible1)
    (iter, amount, eligible)

/-- [poker_settlement_core::side_pot::slice_layer]:
    Source: 'poker-settlement-core/src/side_pot.rs', lines 175:0-190:1 -/
@[reducible]
def side_pot.slice_layer
  (bets : Slice Std.U64) (folded : Slice Bool) (prev_level : Std.U64)
  (level : Std.U64) (n : Std.Usize) :
  Result (Std.U64 × Std.U16)
  := do
  side_pot.slice_layer_loop { start := 0#usize, «end» := n } bets folded
    prev_level level 0#u64 0#u16

/-- [poker_settlement_core::side_pot::calculate_side_pots]: loop body 0:
    Source: 'poker-settlement-core/src/side_pot.rs', lines 139:4-143:5
    Visibility: public -/
@[rust_loop_body]
def side_pot.calculate_side_pots_loop0.body
  (bets : Slice Std.U64) (all_in : Slice Bool)
  (iter : core.ops.range.Range Std.Usize) (levels : alloc.vec.Vec Std.U64) :
  Result (ControlFlow ((core.ops.range.Range Std.Usize) × (alloc.vec.Vec
    Std.U64)) (alloc.vec.Vec Std.U64))
  := do
  let (o, iter1) ←
    core.iter.range.IteratorRange.next core.iter.range.StepUsize iter
  match o with
  | none => ok (done levels)
  | some j =>
    let b ← Slice.index_usize all_in j
    if b
    then
      let i ← Slice.index_usize bets j
      if i > 0#u64
      then
        let levels1 ← side_pot.insert_sorted_u64 levels i
        ok (cont (iter1, levels1))
      else ok (cont (iter1, levels))
    else ok (cont (iter1, levels))

/-- [poker_settlement_core::side_pot::calculate_side_pots]: loop 0:
    Source: 'poker-settlement-core/src/side_pot.rs', lines 139:4-143:5
    Visibility: public -/
@[rust_loop]
def side_pot.calculate_side_pots_loop0
  (iter : core.ops.range.Range Std.Usize) (bets : Slice Std.U64)
  (all_in : Slice Bool) (levels : alloc.vec.Vec Std.U64) :
  Result (alloc.vec.Vec Std.U64)
  := do
  loop
    (fun (iter1, levels1) => side_pot.calculate_side_pots_loop0.body bets
      all_in iter1 levels1)
    (iter, levels)

/-- [poker_settlement_core::side_pot::calculate_side_pots]: loop body 1:
    Source: 'poker-settlement-core/src/side_pot.rs', lines 149:4-156:5
    Visibility: public -/
@[rust_loop_body]
def side_pot.calculate_side_pots_loop1.body
  (bets : Slice Std.U64) (folded : Slice Bool) (n : Std.Usize)
  (iter : core.slice.iter.Iter Std.U64) (pots : alloc.vec.Vec side_pot.SidePot)
  (prev_level : Std.U64) :
  Result (ControlFlow ((core.slice.iter.Iter Std.U64) × (alloc.vec.Vec
    side_pot.SidePot) × Std.U64) ((alloc.vec.Vec side_pot.SidePot) ×
    Std.U64))
  := do
  let (o, iter1) ← core.slice.iter.IteratorSliceIter.next iter
  match o with
  | none => ok (done (pots, prev_level))
  | some level =>
    if level <= prev_level
    then ok (cont (iter1, pots, prev_level))
    else
      let (amount, eligible) ←
        side_pot.slice_layer bets folded prev_level level n
      let pots1 ← side_pot.push_or_merge pots amount eligible
      ok (cont (iter1, pots1, level))

/-- [poker_settlement_core::side_pot::calculate_side_pots]: loop 1:
    Source: 'poker-settlement-core/src/side_pot.rs', lines 149:4-156:5
    Visibility: public -/
@[rust_loop]
def side_pot.calculate_side_pots_loop1
  (iter : core.slice.iter.Iter Std.U64) (bets : Slice Std.U64)
  (folded : Slice Bool) (n : Std.Usize) (pots : alloc.vec.Vec side_pot.SidePot)
  (prev_level : Std.U64) :
  Result ((alloc.vec.Vec side_pot.SidePot) × Std.U64)
  := do
  loop
    (fun (iter1, pots1, prev_level1) => side_pot.calculate_side_pots_loop1.body
      bets folded n iter1 pots1 prev_level1)
    (iter, pots, prev_level)

/-- [poker_settlement_core::side_pot::calculate_side_pots]:
    Source: 'poker-settlement-core/src/side_pot.rs', lines 119:0-170:1
    Visibility: public -/
def side_pot.calculate_side_pots
  (bets : Slice Std.U64) (folded : Slice Bool) (all_in : Slice Bool) :
  Result (core.result.Result side_pot.SidePotResult side_pot.SidePotError)
  := do
  let n := Slice.len bets
  let i := Slice.len folded
  if i != n
  then ok (core.result.Result.Err side_pot.SidePotError.LengthMismatch)
  else
    let i1 := Slice.len all_in
    if i1 != n
    then ok (core.result.Result.Err side_pot.SidePotError.LengthMismatch)
    else
      let i2 ← lift (UScalar.cast .Usize plan.MAX_PLAYERS)
      if n > i2
      then ok (core.result.Result.Err side_pot.SidePotError.LengthMismatch)
      else
        let r ← side_pot.sum_bets bets
        let cf ← core.result.Result.Insts.CoreOpsTry.branch r
        match cf with
        | core.ops.control_flow.ControlFlow.Continue val =>
          let levels ←
            side_pot.calculate_side_pots_loop0
              { start := 0#usize, «end» := n } bets all_in (alloc.vec.Vec.new
              Std.U64)
          let iter ←
            SharedAVec.Insts.CoreIterTraitsCollectIntoIteratorSharedATIter.into_iter
              Global levels
          let (pots, prev_level) ←
            side_pot.calculate_side_pots_loop1 iter bets folded n
              (alloc.vec.Vec.new side_pot.SidePot) 0#u64
          let pots1 ←
            if prev_level < val
            then
              do
              let (amount, eligible) ←
                side_pot.slice_layer bets folded prev_level core.num.U64.MAX n
              side_pot.push_or_merge pots amount eligible
            else ok pots
          let b ← alloc.vec.Vec.is_empty Global pots1
          if b
          then
            let sp ← side_pot.SidePot.new val 0#u16
            let pots2 ← alloc.vec.Vec.push pots1 sp
            ok (core.result.Result.Ok { pots := pots2 })
          else ok (core.result.Result.Ok { pots := pots1 })
        | core.ops.control_flow.ControlFlow.Break residual =>
          core.result.Result.Insts.CoreOpsTry_traitFromResidualResult.from_residual
            side_pot.SidePotResult (core.convert.FromSame
            side_pot.SidePotError) residual

end poker_settlement_core
