-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [poker_settlement_core]: external functions.
-- This is a template file: rename it to "FunsExternal.lean" and fill the holes.
import Aeneas
import PokerSettlementCore.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048
open poker_settlement_core

/-- [alloc::vec::{alloc::vec::Vec<T>}::pop]:
    Source: '/rustc/library/alloc/src/vec/mod.rs', lines 2901:4-2901:38
    Name pattern: [alloc::vec::{alloc::vec::Vec<@T>}::pop]
    Visibility: public -/
@[rust_fun "alloc::vec::{alloc::vec::Vec<@T>}::pop"]
axiom alloc.vec.Vec.pop
  {T : Type} (A : Type) :
  alloc.vec.Vec T → Result ((Option T) × (alloc.vec.Vec T))

/-- [alloc::vec::{alloc::vec::Vec<T>}::is_empty]:
    Source: '/rustc/library/alloc/src/vec/mod.rs', lines 3160:4-3160:40
    Name pattern: [alloc::vec::{alloc::vec::Vec<@T>}::is_empty]
    Visibility: public -/
@[rust_fun "alloc::vec::{alloc::vec::Vec<@T>}::is_empty"]
axiom alloc.vec.Vec.is_empty
  {T : Type} (A : Type) : alloc.vec.Vec T → Result Bool

/-- [alloc::vec::{impl core::iter::traits::collect::IntoIterator<&'a T, core::slice::iter::Iter<'a, T>> for &'a alloc::vec::Vec<T>}::into_iter]:
    Source: '/rustc/library/alloc/src/vec/mod.rs', lines 4088:4-4088:40
    Name pattern: [alloc::vec::{core::iter::traits::collect::IntoIterator<&'a alloc::vec::Vec<@T>, &'a @T, core::slice::iter::Iter<'a, @T>>}::into_iter]
    Visibility: public -/
@[rust_fun
  "alloc::vec::{core::iter::traits::collect::IntoIterator<&'a alloc::vec::Vec<@T>, &'a @T, core::slice::iter::Iter<'a, @T>>}::into_iter"]
axiom SharedAVec.Insts.CoreIterTraitsCollectIntoIteratorSharedATIter.into_iter
  {T : Type} (A : Type) : alloc.vec.Vec T → Result (core.slice.iter.Iter T)

/-- [borsh::de::{impl borsh::de::BorshDeserialize for u64}::deserialize_reader]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/borsh-1.7.0/src/de/mod.rs', lines 201:12-201:74
    Name pattern: [borsh::de::{borsh::de::BorshDeserialize<u64>}::deserialize_reader]
    Visibility: public -/
@[rust_fun "borsh::de::{borsh::de::BorshDeserialize<u64>}::deserialize_reader"]
axiom U64.Insts.BorshDeBorshDeserialize.deserialize_reader
  {R : Type} (allocioreadReadInst : alloc.io.read.Read R) :
  R → Result ((core.result.Result Std.U64 core.io.error.Error) × R)

/-- [borsh::de::{impl borsh::de::BorshDeserialize for u16}::deserialize_reader]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/borsh-1.7.0/src/de/mod.rs', lines 201:12-201:74
    Name pattern: [borsh::de::{borsh::de::BorshDeserialize<u16>}::deserialize_reader]
    Visibility: public -/
@[rust_fun "borsh::de::{borsh::de::BorshDeserialize<u16>}::deserialize_reader"]
axiom U16.Insts.BorshDeBorshDeserialize.deserialize_reader
  {R : Type} (allocioreadReadInst : alloc.io.read.Read R) :
  R → Result ((core.result.Result Std.U16 core.io.error.Error) × R)

/-- [borsh::ser::{impl borsh::ser::BorshSerialize for u64}::serialize]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/borsh-1.7.0/src/ser/mod.rs', lines 81:12-81:71
    Name pattern: [borsh::ser::{borsh::ser::BorshSerialize<u64>}::serialize]
    Visibility: public -/
@[rust_fun "borsh::ser::{borsh::ser::BorshSerialize<u64>}::serialize"]
axiom U64.Insts.BorshSerBorshSerialize.serialize
  {W : Type} (coreiowriteWriteInst : core.io.write.Write W) :
  Std.U64 → W → Result ((core.result.Result Unit core.io.error.Error) × W)

/-- [borsh::ser::{impl borsh::ser::BorshSerialize for u16}::serialize]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/borsh-1.7.0/src/ser/mod.rs', lines 81:12-81:71
    Name pattern: [borsh::ser::{borsh::ser::BorshSerialize<u16>}::serialize]
    Visibility: public -/
@[rust_fun "borsh::ser::{borsh::ser::BorshSerialize<u16>}::serialize"]
axiom U16.Insts.BorshSerBorshSerialize.serialize
  {W : Type} (coreiowriteWriteInst : core.io.write.Write W) :
  Std.U16 → W → Result ((core.result.Result Unit core.io.error.Error) × W)

