-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [poker_settlement_core]: external types.
-- This is a template file: rename it to "TypesExternal.lean" and fill the holes.
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/-- [core::io::error::Error]
    Source: '/rustc/library/core/src/io/error.rs', lines 87:0-87:16
    Name pattern: [core::io::error::Error]
    Visibility: public -/
@[rust_type "core::io::error::Error"]
axiom core.io.error.Error : Type

