-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [poker_settlement_core]: type definitions
import Aeneas
import PokerSettlementCore.TypesExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace poker_settlement_core

/-- Trait declaration: [core::io::write::Write]
    Source: '/rustc/library/core/src/io/write.rs', lines 52:0-52:15
    Name pattern: [core::io::write::Write]
    Visibility: public -/
@[rust_trait "core::io::write::Write"]
structure core.io.write.Write (Self : Type) where
  write : Self → Slice Std.U8 → Result ((core.result.Result Std.Usize
    core.io.error.Error) × Self)
  flush : Self → Result ((core.result.Result Unit core.io.error.Error) ×
    Self)

/-- Trait declaration: [alloc::io::read::Read]
    Source: '/rustc/library/alloc/src/io/read.rs', lines 87:0-87:14
    Name pattern: [alloc::io::read::Read]
    Visibility: public -/
@[rust_trait "alloc::io::read::Read"]
structure alloc.io.read.Read (Self : Type) where

/-- Trait declaration: [borsh::de::BorshDeserialize]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/borsh-1.7.0/src/de/mod.rs', lines 36:0-36:33
    Name pattern: [borsh::de::BorshDeserialize]
    Visibility: public -/
@[rust_trait "borsh::de::BorshDeserialize"]
structure borsh.de.BorshDeserialize (Self : Type) where
  deserialize_reader : forall {R : Type} (allocioreadReadInst :
    alloc.io.read.Read R), R → Result ((core.result.Result Self
    core.io.error.Error) × R)

/-- Trait declaration: [borsh::ser::BorshSerialize]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/borsh-1.7.0/src/ser/mod.rs', lines 51:0-51:24
    Name pattern: [borsh::ser::BorshSerialize]
    Visibility: public -/
@[rust_trait "borsh::ser::BorshSerialize"]
structure borsh.ser.BorshSerialize (Self : Type) where
  serialize : forall {W : Type} (coreiowriteWriteInst : core.io.write.Write W),
    Self → W → Result ((core.result.Result Unit core.io.error.Error) × W)

/-- [poker_settlement_core::side_pot::SidePot]
    Source: 'poker-settlement-core/src/side_pot.rs', lines 36:0-41:1
    Visibility: public -/
structure side_pot.SidePot where
  amount : Std.U64
  eligible_seats : Std.U16

/-- [poker_settlement_core::side_pot::SidePotError]
    Source: 'poker-settlement-core/src/side_pot.rs', lines 62:0-69:1
    Visibility: public -/
@[discriminant isize]
inductive side_pot.SidePotError where
| BetOverflow : side_pot.SidePotError
| LengthMismatch : side_pot.SidePotError

/-- [poker_settlement_core::side_pot::SidePotResult]
    Source: 'poker-settlement-core/src/side_pot.rs', lines 76:0-79:1
    Visibility: public -/
structure side_pot.SidePotResult where
  pots : alloc.vec.Vec side_pot.SidePot

end poker_settlement_core
